<?php
require_once '/etc/zpanel/panel/cnf/db.php';
require_once '/etc/zpanel/panel/dryden/db/driver.class.php';

try {
    $database = new db_driver("mysql:host=$host;dbname=$dbname", $user, $pass);
    $database->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (PDOException $e) {
    die($e);
}

// Drop the table - deletes all rows
$query = "DROP TABLE `x_ai_apps`";
$database->bindQuery($query);